/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
    './constants/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#560038',
        'on-secondary-container': '#00424e',
        'surface-container-high': '#2a2a2a',
        'surface-container': '#201f1f',
        'on-surface': '#e5e2e1',
        secondary: '#4cd7f6',
        'on-error-container': '#ffdad6',
        'surface-dim': '#131313',
        'surface-container-highest': '#353534',
        'on-tertiary-fixed-variant': '#85145a',
        'on-primary-fixed': '#2c0051',
        'secondary-fixed': '#acedff',
        'surface-bright': '#3a3939',
        'on-secondary': '#003640',
        background: '#000000',
        outline: '#988d9f',
        'on-primary': '#490080',
        'on-secondary-fixed-variant': '#004e5c',
        'surface-container-low': '#1c1b1b',
        'on-secondary-fixed': '#001f26',
        error: '#ffb4ab',
        'on-primary-fixed-variant': '#6900b3',
        'surface-tint': '#ddb7ff',
        'primary-container': '#b76dff',
        'on-primary-container': '#400071',
        'tertiary-container': '#e364a7',
        'tertiary-fixed-dim': '#ffafd3',
        'inverse-primary': '#842bd2',
        'inverse-surface': '#e5e2e1',
        'on-error': '#690005',
        'secondary-fixed-dim': '#4cd7f6',
        'surface-container-lowest': '#0e0e0e',
        'on-tertiary-fixed': '#3d0026',
        surface: '#131313',
        'primary-fixed': '#f0dbff',
        'on-background': '#e5e2e1',
        tertiary: '#ffafd3',
        'secondary-container': '#03b5d3',
        'on-tertiary': '#620040',
        'outline-variant': '#4d4354',
        'primary-fixed-dim': '#ddb7ff',
        'inverse-on-surface': '#313030',
        'tertiary-fixed': '#ffd8e7',
        'surface-variant': '#353534',
        primary: '#ddb7ff',
        'on-surface-variant': '#cfc2d6',
        'error-container': '#93000a',
      },
      spacing: {
        'container-margin-desktop': '40px',
        'section-gap': '80px',
        'container-margin-mobile': '20px',
        'stack-unit': '8px',
        gutter: '24px',
      },
      fontFamily: {
        'headline-lg-mobile': ['System'],
        'label-sm': ['System'],
        'body-md': ['System'],
        'body-lg': ['System'],
        'headline-xl': ['System'],
        'headline-lg': ['System'],
        'label-md': ['System'],
      },
      fontSize: {
        'headline-lg-mobile': [
          '28px',
          { lineHeight: '34px', fontWeight: '700' },
        ],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': [
          '48px',
          { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '800' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' },
        ],
        'label-md': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' },
        ],
      },
    },
  },
  plugins: [],
};
